/********************************************************************************
** Form generated from reading UI file 'GcodeReference.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GCODEREFERENCE_H
#define UI_GCODEREFERENCE_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GcodeReference
{
public:
    QGridLayout *gridLayout;
    QHBoxLayout *horizontalLayout;
    QListWidget *listWidget;
    QVBoxLayout *verticalLayout;
    QTextEdit *teMacro;
    QTextEdit *textEdit;

    void setupUi(QWidget *GcodeReference)
    {
        if (GcodeReference->objectName().isEmpty())
            GcodeReference->setObjectName(QString::fromUtf8("GcodeReference"));
        GcodeReference->resize(1219, 751);
        GcodeReference->setMaximumSize(QSize(16777201, 16777215));
        GcodeReference->setLayoutDirection(Qt::LeftToRight);
        GcodeReference->setAutoFillBackground(false);
        gridLayout = new QGridLayout(GcodeReference);
        gridLayout->setSpacing(0);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(0, 0, 0, 0);
        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setSpacing(0);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        listWidget = new QListWidget(GcodeReference);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setMinimumSize(QSize(200, 0));
        listWidget->setMaximumSize(QSize(400, 16777215));

        horizontalLayout->addWidget(listWidget);

        verticalLayout = new QVBoxLayout();
        verticalLayout->setSpacing(6);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        teMacro = new QTextEdit(GcodeReference);
        teMacro->setObjectName(QString::fromUtf8("teMacro"));

        verticalLayout->addWidget(teMacro);

        textEdit = new QTextEdit(GcodeReference);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setMinimumSize(QSize(400, 0));
        textEdit->setAcceptRichText(true);
        textEdit->setTextInteractionFlags(Qt::TextSelectableByKeyboard|Qt::TextSelectableByMouse);

        verticalLayout->addWidget(textEdit);


        horizontalLayout->addLayout(verticalLayout);


        gridLayout->addLayout(horizontalLayout, 0, 0, 1, 1);


        retranslateUi(GcodeReference);

        QMetaObject::connectSlotsByName(GcodeReference);
    } // setupUi

    void retranslateUi(QWidget *GcodeReference)
    {
        GcodeReference->setWindowTitle(QCoreApplication::translate("GcodeReference", "Gcode Reference", nullptr));

        const bool __sortingEnabled = listWidget->isSortingEnabled();
        listWidget->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget->item(0);
        ___qlistwidgetitem->setText(QCoreApplication::translate("GcodeReference", "1. GOTO", nullptr));
        QListWidgetItem *___qlistwidgetitem1 = listWidget->item(1);
        ___qlistwidgetitem1->setText(QCoreApplication::translate("GcodeReference", "2. IF", nullptr));
        QListWidgetItem *___qlistwidgetitem2 = listWidget->item(2);
        ___qlistwidgetitem2->setText(QCoreApplication::translate("GcodeReference", "3. Conditional Expressions", nullptr));
        QListWidgetItem *___qlistwidgetitem3 = listWidget->item(3);
        ___qlistwidgetitem3->setText(QCoreApplication::translate("GcodeReference", "4. Variables", nullptr));
        QListWidgetItem *___qlistwidgetitem4 = listWidget->item(4);
        ___qlistwidgetitem4->setText(QCoreApplication::translate("GcodeReference", "5. Define Subprograms", nullptr));
        QListWidgetItem *___qlistwidgetitem5 = listWidget->item(5);
        ___qlistwidgetitem5->setText(QCoreApplication::translate("GcodeReference", "6. Call Subprograms", nullptr));
        QListWidgetItem *___qlistwidgetitem6 = listWidget->item(6);
        ___qlistwidgetitem6->setText(QCoreApplication::translate("GcodeReference", "7. Vision Functions", nullptr));
        QListWidgetItem *___qlistwidgetitem7 = listWidget->item(7);
        ___qlistwidgetitem7->setText(QCoreApplication::translate("GcodeReference", "G0, G1 - Linear Move", nullptr));
        QListWidgetItem *___qlistwidgetitem8 = listWidget->item(8);
        ___qlistwidgetitem8->setText(QCoreApplication::translate("GcodeReference", "G2, G3 - Controlled Arc Move", nullptr));
        QListWidgetItem *___qlistwidgetitem9 = listWidget->item(9);
        ___qlistwidgetitem9->setText(QCoreApplication::translate("GcodeReference", "G4 - Dwell", nullptr));
        QListWidgetItem *___qlistwidgetitem10 = listWidget->item(10);
        ___qlistwidgetitem10->setText(QCoreApplication::translate("GcodeReference", "G5 - Bezier cubic spline", nullptr));
        QListWidgetItem *___qlistwidgetitem11 = listWidget->item(11);
        ___qlistwidgetitem11->setText(QCoreApplication::translate("GcodeReference", "G6 - Controlled Angle", nullptr));
        QListWidgetItem *___qlistwidgetitem12 = listWidget->item(12);
        ___qlistwidgetitem12->setText(QCoreApplication::translate("GcodeReference", "G28 - Auto Home", nullptr));
        QListWidgetItem *___qlistwidgetitem13 = listWidget->item(13);
        ___qlistwidgetitem13->setText(QCoreApplication::translate("GcodeReference", "G90 - Absolute Positioning", nullptr));
        QListWidgetItem *___qlistwidgetitem14 = listWidget->item(14);
        ___qlistwidgetitem14->setText(QCoreApplication::translate("GcodeReference", "G91 - Relative Positioning", nullptr));
        QListWidgetItem *___qlistwidgetitem15 = listWidget->item(15);
        ___qlistwidgetitem15->setText(QCoreApplication::translate("GcodeReference", "M3 - Spindle CW/ Laser On/ Set Gripper To Close/ Set Angle of Gripper", nullptr));
        QListWidgetItem *___qlistwidgetitem16 = listWidget->item(16);
        ___qlistwidgetitem16->setText(QCoreApplication::translate("GcodeReference", "M4 - Spindle CCW/ Laser On/ Set Gripper To Close/ Set Angle of Gripper", nullptr));
        QListWidgetItem *___qlistwidgetitem17 = listWidget->item(17);
        ___qlistwidgetitem17->setText(QCoreApplication::translate("GcodeReference", "M5 - Spindle / Laser Off/ Gripper Open", nullptr));
        QListWidgetItem *___qlistwidgetitem18 = listWidget->item(18);
        ___qlistwidgetitem18->setText(QCoreApplication::translate("GcodeReference", "M84 - Disable steppers", nullptr));
        QListWidgetItem *___qlistwidgetitem19 = listWidget->item(19);
        ___qlistwidgetitem19->setText(QCoreApplication::translate("GcodeReference", "M104 - Set Hotend Temperature", nullptr));
        QListWidgetItem *___qlistwidgetitem20 = listWidget->item(20);
        ___qlistwidgetitem20->setText(QCoreApplication::translate("GcodeReference", "M109 - Wait for Hotend Temperature", nullptr));
        QListWidgetItem *___qlistwidgetitem21 = listWidget->item(21);
        ___qlistwidgetitem21->setText(QCoreApplication::translate("GcodeReference", "M203 - Set Max Feedrate", nullptr));
        QListWidgetItem *___qlistwidgetitem22 = listWidget->item(22);
        ___qlistwidgetitem22->setText(QCoreApplication::translate("GcodeReference", "M204 - Set Acceleration", nullptr));
        QListWidgetItem *___qlistwidgetitem23 = listWidget->item(23);
        ___qlistwidgetitem23->setText(QCoreApplication::translate("GcodeReference", "M205 - Set begin speed", nullptr));
        QListWidgetItem *___qlistwidgetitem24 = listWidget->item(24);
        ___qlistwidgetitem24->setText(QCoreApplication::translate("GcodeReference", "M206 - Set Z Offsets", nullptr));
        QListWidgetItem *___qlistwidgetitem25 = listWidget->item(25);
        ___qlistwidgetitem25->setText(QCoreApplication::translate("GcodeReference", "M330 - Set External Serial Port 1", nullptr));
        QListWidgetItem *___qlistwidgetitem26 = listWidget->item(26);
        ___qlistwidgetitem26->setText(QCoreApplication::translate("GcodeReference", "M331 - Set External Serial Port 2", nullptr));
        QListWidgetItem *___qlistwidgetitem27 = listWidget->item(27);
        ___qlistwidgetitem27->setText(QCoreApplication::translate("GcodeReference", "M500 - Save Settings", nullptr));
        QListWidgetItem *___qlistwidgetitem28 = listWidget->item(28);
        ___qlistwidgetitem28->setText(QCoreApplication::translate("GcodeReference", "M501 - Restore Settings", nullptr));
        QListWidgetItem *___qlistwidgetitem29 = listWidget->item(29);
        ___qlistwidgetitem29->setText(QCoreApplication::translate("GcodeReference", "M502 - Restore Settings", nullptr));
        QListWidgetItem *___qlistwidgetitem30 = listWidget->item(30);
        ___qlistwidgetitem30->setText(QCoreApplication::translate("GcodeReference", "M360 - Set End effector", nullptr));
        QListWidgetItem *___qlistwidgetitem31 = listWidget->item(31);
        ___qlistwidgetitem31->setText(QCoreApplication::translate("GcodeReference", "M361 - Set mm per linear segment", nullptr));
        QListWidgetItem *___qlistwidgetitem32 = listWidget->item(32);
        ___qlistwidgetitem32->setText(QCoreApplication::translate("GcodeReference", "M362 - Set mm per arc segment", nullptr));
        QListWidgetItem *___qlistwidgetitem33 = listWidget->item(33);
        ___qlistwidgetitem33->setText(QCoreApplication::translate("GcodeReference", "M310 - Set Speed Mode", nullptr));
        QListWidgetItem *___qlistwidgetitem34 = listWidget->item(34);
        ___qlistwidgetitem34->setText(QCoreApplication::translate("GcodeReference", "M311 - Set Speed", nullptr));
        QListWidgetItem *___qlistwidgetitem35 = listWidget->item(35);
        ___qlistwidgetitem35->setText(QCoreApplication::translate("GcodeReference", "M312 - Set Position", nullptr));
        QListWidgetItem *___qlistwidgetitem36 = listWidget->item(36);
        ___qlistwidgetitem36->setText(QCoreApplication::translate("GcodeReference", "M313 - Set Speed for Position Moving ", nullptr));
        QListWidgetItem *___qlistwidgetitem37 = listWidget->item(37);
        ___qlistwidgetitem37->setText(QCoreApplication::translate("GcodeReference", "M320 - Go To Home", nullptr));
        QListWidgetItem *___qlistwidgetitem38 = listWidget->item(38);
        ___qlistwidgetitem38->setText(QCoreApplication::translate("GcodeReference", "M321 - Set Speed", nullptr));
        QListWidgetItem *___qlistwidgetitem39 = listWidget->item(39);
        ___qlistwidgetitem39->setText(QCoreApplication::translate("GcodeReference", "M322 - Set Position", nullptr));
        QListWidgetItem *___qlistwidgetitem40 = listWidget->item(40);
        ___qlistwidgetitem40->setText(QCoreApplication::translate("GcodeReference", "M323 - Disable Stepper Motor", nullptr));
        QListWidgetItem *___qlistwidgetitem41 = listWidget->item(41);
        ___qlistwidgetitem41->setText(QCoreApplication::translate("GcodeReference", "Some other commands", nullptr));
        listWidget->setSortingEnabled(__sortingEnabled);

        teMacro->setHtml(QCoreApplication::translate("GcodeReference", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Allerta'; font-size:16pt; font-weight:600; color:#007bff; background-color:#fafafa;\">G-Code Macro Programming</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"1\"></a><span style=\" font-size:10pt; font-weight:600;\">1</span><span style=\" font-size:10pt; fo"
                        "nt-weight:600;\">. GOTO - Jumping Ahead in G-Code</span><span style=\" font-size:10pt;\"><br />Sometimes we don\342\200\231t want to just keep executing g-code one block after the other from top to bottom. It can be helpful if the g-code jumps around. We\342\200\231ve seen some of this jumping in the form of subprogram and macro calls, but those are specialized kinds of jumps that assume you\342\200\231ll want to pick up right after the jump after the subprogram or macro finishes. GOTO is pretty simple to use, it\342\200\231s just </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">GOTO </span><span style=\" font-size:10pt;\">followed by the sequence number (\342\200\234</span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">N</span><span style=\" font-size:10pt;\">\342\200\235 number) you\342\200\231d like to jump to.<br /><br />For example:<br /></span><span style=\" font-size:10pt; color:#38761d;\">N100 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;"
                        "\">GOTO </span><span style=\" font-size:10pt; color:#38761d;\">120 </span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\">N110 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">G01 </span><span style=\" font-size:10pt; color:#38761d;\">X100 Y-100 Z-300</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\">N120</span><span style=\" font-size:10pt;\">                                             (GOTO jumps directly here)<br /><br />That program snippet uses a GOTO whose address is \342\200\234120\342\200\235 to jump over N110 and go directly to N120.<br /><br /></span><a name=\"2\"></a><span style=\" font-size:10pt; font-weight:600;\">2</span><span style=\" font-size:10pt; font-weight:600;\">. IF - Conditional Branching</span><span style=\" font-size:10pt;\"><br />While GOTO represents an \342\200\234unconditional branch\342\200\235 in G-Code execution, IF allows for \342\200\234conditional branching"
                        "\342\200\235.<br />Imagine being able to ask a question, and perform the GOTO only if the answer to the question is \342\200\234Yes\342\200\235.<br />In essence, that\342\200\231s what the IF does:<br /><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">IF</span><span style=\" font-size:10pt;\"> [condition is true] </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">GOTO</span><span style=\" font-size:10pt;\"> x<br /><br />The entity enclosed in the square brackets is called a \342\200\234conditional expression\342\200\235, and they don\342\200\231t really look like \342\200\234condition is true\342\200\235, that\342\200\231s just an English translation of their general form.<br /><br />Instead, Conditional Expression consist of a comparison of some kind:<br /><br /></span><span style=\" font-size:10pt; color:#38761d;\">\342\200\246</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\"><br /></span><span style=\" font-"
                        "size:10pt; font-weight:600; color:#38761d;\">IF</span><span style=\" font-size:10pt; color:#38761d;\"> [#100 EQ 0] </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">GOTO</span><span style=\" font-size:10pt; color:#38761d;\"> 110</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\"><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">GOTO</span><span style=\" font-size:10pt; color:#38761d;\"> 200</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\"><br />\342\200\246</span><span style=\" font-size:10pt;\"><br /><br />That \342\200\234[#100 EQ 0]\342\200\235 is a conditional expression that checks whether the value of #100 is zero.<br />If it is, the G-Code will perform a GOTO taking it to N110.<br />If its value isn\342\200\231t zero, the G-Code falls through to the next line, which we see is an alternate GOTO that takes us to N200.<br />That\342\200\231s how conditional b"
                        "ranching with IF and GOTO work together. Note that the line following the IF statement could have been anything, it doesn\342\200\231t have to be a GOTO.<br /><br />But what if we wanted to do something other than \342\200\234GOTO\342\200\235 if #100 is equal to zero?<br />Perhaps we simply want to change the value of #100 so it isn\342\200\231t zero, avoiding a potential divide by zero problem down the line.<br />When we want to do something other than GOTO, we use an \342\200\234</span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">IF</span><span style=\" font-size:10pt;\">..</span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">THEN</span><span style=\" font-size:10pt;\">\342\200\235 statement:<br /><br /></span><span style=\" font-size:10pt; color:#38761d;\">\342\200\246</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\"><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">IF </span><span style=\" f"
                        "ont-size:10pt; color:#38761d;\">[#100 EQ 0] </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">THEN </span><span style=\" font-size:10pt; color:#38761d;\">#100 = 1 </span><span style=\" font-size:10pt;\">(Avoid dividing by zero!)<br /></span><span style=\" font-size:10pt; color:#38761d;\"><br />#110 = #105 / #100</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\"><br />\342\200\246</span><span style=\" font-size:10pt;\"><br /><br /></span><a name=\"3\"></a><span style=\" font-size:10pt; font-weight:600;\">3</span><span style=\" font-size:10pt; font-weight:600;\">. Conditional Expressions</span><span style=\" font-size:10pt;\"><br />Let\342\200\231s talk about the rules for Conditional Expressions.<br />Not just any expression can be a conditional expression.<br />Here are the rules:<br /><br />\342\200\223 Conditional expressions must be enclosed in square brackets (\342\200\234</span><span style=\" font-size:10pt; font-weight:600; color:#38"
                        "761d;\">[</span><span style=\" font-size:10pt;\">\342\200\235 and \342\200\234</span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">]</span><span style=\" font-size:10pt;\">\342\200\235).<br /><br />\342\200\223 A Conditional Expression consists of two operands and a comparison operator.<br /><br />\342\200\223 An operand may be a # variable or a number.<br /><br />\342\200\223 Comparison Operators:<br /><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">EQ</span><span style=\" font-size:10pt;\">: Equal<br /><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">NE</span><span style=\" font-size:10pt;\">: Not equal<br /><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">GT</span><span style=\" font-size:10pt;\">: Greater than<br /><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">GE</span><span style=\" font-size:10pt;\">: Greater than or equal<br /><br /></span><span style=\" font-size:10"
                        "pt; font-weight:600; color:#38761d;\">LT</span><span style=\" font-size:10pt;\">: Less than<br /><br /></span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">LE</span><span style=\" font-size:10pt;\">: Less than or equal<br /><br />\342\200\223 Comparisons may be further grouped with square brackets and </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">AND</span><span style=\" font-size:10pt;\">, </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">OR</span><span style=\" font-size:10pt;\">, or </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">XOR</span><span style=\" font-size:10pt;\">. For example:<br /><br /></span><span style=\" font-size:10pt; color:#38761d;\">[[0 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">LE </span><span style=\" font-size:10pt; color:#38761d;\">#100] </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">AND </span><span style=\" font-size:10pt; color:#38761d;\">"
                        "[#100 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">LE </span><span style=\" font-size:10pt; color:#38761d;\">1000]]</span><span style=\" font-size:10pt;\"> (True if the value of #100 is 0 to 1000)<br /><br /></span><a name=\"4\"></a><span style=\" font-size:10pt; font-weight:600;\">4</span><span style=\" font-size:10pt; font-weight:600;\">. Variables</span><span style=\" font-size:10pt;\"><br />First thing is first, what are variables?<br />Simply put, they are just like algebra variables that you can use in your g-code.<br />They can be assigned values, and when you refer to them, they give back the last value they were assigned.<br /><br />The syntax for a variable is the pound sign followed by a number up to however many digits your controller supports that identifies the variable.<br />For example, we can write<br /></span><span style=\" font-size:10pt; color:#38761d;\">\342\200\234</span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">#1</span><span style=\" fon"
                        "t-size:10pt; color:#38761d;\"> = 100\342\200\235</span><span style=\" font-size:10pt;\"><br />to assign the value \342\200\234100\342\200\235 to the variable \342\200\234</span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">#1</span><span style=\" font-size:10pt;\">\342\200\235.<br /><br /></span><a name=\"5\"></a><span style=\" font-size:10pt; font-weight:600;\">5</span><span style=\" font-size:10pt; font-weight:600;\">. Define Subprograms</span><span style=\" font-size:10pt;\"><br />Ex:<br /></span><span style=\" font-size:10pt; color:#38761d;\">N565 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">O2008 </span><span style=\" font-size:10pt; font-weight:600;\"> </span><span style=\" font-size:10pt;\">(Begin subprogram, &quot;2008&quot; is the name)<br /></span><span style=\" font-size:10pt; color:#38761d;\">N570 G01 X0 Y-120  </span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\">N575 G04 P100            </span><span style"
                        "=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\">N580 G01 Z-300</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; color:#38761d;\"><br />N585 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">M99</span><span style=\" font-size:10pt; font-weight:600;\"> </span><span style=\" font-size:10pt;\">(End subprogram)<br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span><a name=\"6\"></a><span style=\" font-size:10pt; font-weight:600;\">6</span><span style=\" font-size:10pt; font-weight:600;\">. Call Subprograms</span><span style=\" font-size:10pt;\"><br />Ex:<br /></span><span style=\" font-size:10pt; color:#38761d;\">N700 </span><span style=\" font-size:10pt; font-weight:600; color:#38761d;\">M98</span><span style=\" font-size:10pt; color:#38761d;\"> </span><span style=\" font-size:10pt; font-weigh"
                        "t:600; color:#38761d;\">P2008 </span><span style=\" font-size:10pt;\">( &quot;2008&quot; is the name of subprogram)<br /><br /></span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\"><br /></span><span style=\" font-size:12pt;\">====</span><a name=\"7\"></a><span style=\" font-size:12pt; font-weight:600;\">V</span><span style=\" font-size:12pt; font-weight:600;\">ision functions</span><span style=\" font-size:12pt;\">====</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">M98 PpauseCamera</span><span style=\" font-size:10pt;\"> - Pause reading frames from the camera</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px"
                        "; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">M98 PresumeCamera</span><span style=\" font-size:10pt;\"> - Resume reading camera</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">M98 PcaptureCamera</span><span style=\" font-size:10pt;\"> - Capture a frame from camera</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-le"
                        "ft:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">M98 PdeleteFirstObject</span><span style=\" font-size:10pt;\"> - Delete the first element in the container of the tracking objects</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">M98 PclearObjects</span><span style=\" font-size:10pt;\"> - Clear all tracking objects in container</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><sp"
                        "an style=\" font-size:10pt;\">========================</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\"><br /></span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; font-weight:600; color:#741b47;\">G-Code Macro Programming Example</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-size:10pt; font-weight:600; color:#741b47;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#38761d;\">;------------------------------------------------------------------</span><span style=\" font-size:10pt;\"><br /><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">N05</span><span style=\" font-size:10pt;\"> </span><span style=\" font-size:10pt; font-weight:600;\">G28</s"
                        "pan></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N10 </span><span style=\" font-size:10pt; font-weight:600;\">M204</span><span style=\" font-size:10pt;\"> A1200</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N15 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> F200</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#00aa00;\">;Declare a variable</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N20 </span><span style=\" font-size:10pt; font-style:italic;\">#100</span><"
                        "span style=\" font-size:10pt;\"> = 0</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N30 </span><span style=\" font-size:10pt; font-style:italic;\">#100</span><span style=\" font-size:10pt;\"> = </span><span style=\" font-size:10pt; font-style:italic;\">#100</span><span style=\" font-size:10pt;\"> + 1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#55aa00;\">;Call subprogram</span></p>\n"
"<p style=\" ma"
                        "rgin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N35 </span><span style=\" font-size:10pt; font-weight:600;\">M98</span><span style=\" font-size:10pt;\"> P2000</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#00aa00;\">; Begin subprogram</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N40 </span><span style=\" font-size:10pt; font-weight:600;\">O2000</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><spa"
                        "n style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N45 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> Z-350</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N50 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> X-100</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N55 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> Z-370</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\""
                        " font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N60 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> Z-350</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N65 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> X100</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N70 </span><span style=\" font-size:10pt; font-weight:600;\">G01</span><span style=\" font-size:10pt;\"> Z-370</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size"
                        ":10pt;\">N75 M99</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#00aa00;\">;End subprogram</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#00aa00;\">;Loop 5 times</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N80 </span><span style=\" font-size:10pt; font-weight:600; color:#00aa00;\">IF</span><span style=\" font-size:10pt;\"> [</span><span style=\" font-size:10pt; font-style:italic;\">#100</span><span style=\" font-size:10pt;\"> LE "
                        "5] </span><span style=\" font-size:10pt; font-weight:600; color:#00aa00;\">THEN</span><span style=\" font-size:10pt;\"> </span><span style=\" font-size:10pt; font-weight:600; color:#ff5500;\">GOTO</span><span style=\" font-size:10pt;\"> 30</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">N85 </span><span style=\" font-size:10pt; font-weight:600;\">G28</span></p></body></html>", nullptr));
#if QT_CONFIG(tooltip)
        textEdit->setToolTip(QString());
#endif // QT_CONFIG(tooltip)
        textEdit->setHtml(QCoreApplication::translate("GcodeReference", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Allerta'; font-size:16pt; font-weight:600; color:#007bff; background-color:#fafafa;\">Delta X Firmware Gcode</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-we"
                        "ight:600;\"><br /></span><a name=\"G0_G1\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">0, G1 \342\200\223 Linear Move</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: The G0 and G1 commands add a linear move to the queue to be performed after all previous moves are completed.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">A command like G1 F1000 sets the feedrate for all subsequent moves.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G0 [F&lt;rate&gt;] [X&lt;pos&gt;] [Y&lt;pos&gt;] [Z&lt;pos&gt;] [W&lt;ang&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,s"
                        "ans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[F&lt;rate&gt;]    The maximum movement rate of the move between the start and end point. The feedrate set here applies to subsequent moves that omit this parameter.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[X&lt;pos&gt;]   A coordinate on the X axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Y&lt;pos&gt;]   A coordinate on the Y axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Z&lt;pos&gt;]   A coordinate on the Z axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[W&lt;ang&gt;]   A coordinate on the W axis.</s"
                        "pan><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Examples:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G0 X12   ; move to 12mm on the X axis </span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G0 F1500 ; set the feedrate to 1500mm/minute </span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G1 X90.6 Y13.8 ; move to 90.6mm on the X axis and 13.8mm on the Y axis </span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"G2_G3\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\""
                        ">2, G3 \342\200\223 Controlled Arc Move</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: G2 adds a clockwise arc move to the planner; G3 adds a counter-clockwise arc. An arc move starts at the current position and ends at the given XYZ, pivoting around a center-point offset given by I and J.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G2 [F&lt;rate&gt;] I&lt;offset&gt; J&lt;offset&gt; [X&lt;pos&gt;] [Y&lt;pos&gt;] [W&lt;ang&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[F&lt;rate&gt;]    The maximum movement rate of the move between the start and end point. The feedrate set here applies to subsequent moves that "
                        "omit this parameter.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">I&lt;offset&gt;   An offset from the current X position to use as the arc center.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">J&lt;offset&gt;   An offset from the current Y position to use as the arc center.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[X&lt;pos&gt;]   A coordinate on the X axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Y&lt;pos&gt;]   A coordinate on the Y axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[W&lt;ang&gt;]   A coordinate on the W axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" fon"
                        "t-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Examples:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G2 I40 J0 X80 Y0</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"G4\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">4 \342\200\223 Dwell</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Dwell pauses the command queue and waits for a period of time.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G4 [P&lt;time in ms&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'"
                        "arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[P&lt;time in ms&gt;]   Amount of time to dwell.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Examples:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G4 P500 ; delay 0.5s</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"G5\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">5 \342\200\223 Bezier cubic spline</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:"
                        "10pt;\">Description: G5 creates a cubic B-spline in the XY plane with the X and Y axes only. P and Q parameters are required. I and J are required for the first G5 command in a series. For subsequent G5commands, either both I and J must be specified, or neither. If I and J are unspecified, the starting direction of the cubic will automatically match the ending direction of the previous cubic (as if I and J are the negation of the previous P and Q).</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G5 [F&lt;rate&gt;] I&lt;pos&gt; J&lt;pos&gt; P&lt;pos&gt; Q&lt;pos&gt; X&lt;pos&gt; Y&lt;pos&gt;  [W&lt;ang&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[F&lt;rate&gt;]    The maximum movement rate of the move be"
                        "tween the start and end point. The feedrate set here applies to subsequent moves that omit this parameter.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[I&lt;pos&gt;]   X incremental offset from start point to first control point.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[J&lt;pos&gt;]   Y incremental offset from start point to first control point.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[P&lt;pos&gt;]  X incremental offset from end point to second control point.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Q&lt;pos&gt;]   Y incremental offset from end point to second control point.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,s"
                        "ans-serif'; font-size:10pt;\">[X&lt;pos&gt;]   A coordinate on the Y axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Y&lt;pos&gt;]   A coordinate on the Y axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[W&lt;ang&gt;]   A coordinate on the W axis.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Examples:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G5 F200 I-40 Y20 P-20 Y-20 X20 Y-20.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /><br /></span><a name=\"G6\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvet"
                        "ica,sans-serif'; font-size:10pt; font-weight:600;\">6 \342\200\223 Controlled Angle</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Directly control movement angle without endpoint coordinates..</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G6 [F&lt;rate&gt;] X&lt;pos&gt; Y&lt;pos&gt; Z&lt;pos&gt; P&lt;pos&gt;</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[F&lt;rate&gt;]    The maximum movement rate of the move between the start and end point. The feedrate set here applies to subsequent moves that omit this parameter.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-"
                        "serif'; font-size:10pt;\">[X&lt;pos&gt;]   The value of the angle theta 1.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Y&lt;pos&gt;]   The value of the angle theta 2.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[Z&lt;pos&gt;]   The value of the angle theta 3.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[P&lt;pos&gt;]   Distance traveled.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Examples:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">G4 P500 ; delay 0.5s</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\""
                        "G28\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">28 \342\200\223 Auto Home</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Auto-home one or more axes, moving them towards their endstops until triggered.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G28</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"G90\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">90 \342\200\223 Absolute Positioning</span><span style=\" font-size:10pt;\"><br /></spa"
                        "n><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: In absolute mode all coordinates given in G-code are interpreted as positions in the logical coordinate space.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G90</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"G91\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">G</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">91 \342\200\223 Relative Positioning</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Set relative position mode. In this mode all coordinates are interpreted as relative to the last position.</span><span style=\" font-size:10pt;\"><br /></spa"
                        "n><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: G91</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M3\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">3 \342\200\223 Spindle CW/ Laser On/ Set Gripper To Close/ Set Angle of Gripper</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Wait for moves to complete, then set the spindle speed (clockwise), laser power, or angle of gripper.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M3 [S&lt;value&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; f"
                        "ont-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[S&lt;value&gt;] Spindle speed (0 - 255), laser power (0 - 255), angle of gripper (0-100), if value is emtpy then gripper close.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /><br /></span><a name=\"M4\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">4 \342\200\223 Spindle CCW/ Laser On/ Set Gripper To Close/ Set Angle of Gripper</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Wait for moves to complete, then set the spindle speed (clockwise), laser power, or angle of gripper.</span><span style=\" font-size:10pt;\"><br /></span><span st"
                        "yle=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M4 [S&lt;value&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[S&lt;value&gt;] Spindle speed (0 - 255), laser power (0 - 255), angle of gripper (0-100), if value is emtpy then gripper close.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M5\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">5 \342\200\223 Spindle / Laser Off/ Gripper Open</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Descripti"
                        "on: Wait for moves to complete, then turn off the spindle / laser power, PWM and set gripper to open.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M5</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M84\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">84 \342\200\223 Disable steppers</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: This command can be used to disable steppers.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M84</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-famil"
                        "y:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M104\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">104 \342\200\223 Set Hotend Temperature</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Set a new target hot end temperature and continue without waiting. The firmware will continue to try to reach and hold the temperature in the background.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M104 [S&lt;temp&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10"
                        "pt;\">[S&lt;temp&gt;] Target temperature.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M109\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">109 \342\200\223 Wait for Hotend Temperature</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: This command optionally sets a new target hot end temperature and waits for the target temperature to be reached before proceeding.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M109 [S&lt;temp&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\""
                        " font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[S&lt;temp&gt;] Target temperature.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M203\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">203 \342\200\223 Set Max Feedrate</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Set the max feedrate for one or more axes.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M203 [S&lt;units/s&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span sty"
                        "le=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[S&lt;units/s&gt;] Max feedrate.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /><br /></span><a name=\"M204\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">204 \342\200\223 Set Acceleration</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Set the preferred acceleration for moves of different types.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M204 [A&lt;accel&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Par"
                        "ameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[S&lt;accel&gt;] Travel acceleration.</span><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"M205\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529; background-color:#ffffff;\">M</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529; background-color:#ffffff;\">205 \342\200\223 Set begin speed</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Robot"
                        "o,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Description:  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Usage: M205 [S&lt;units/s&gt;] </span></p>\n"
"<p style=\" margin-top:0px"
                        "; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Parameters: [S&lt;mm/s&gt;] begin speed.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"gcode-content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529;\">M</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe U"
                        "I Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529;\">206 \342\200\223 Set X Y Z Offsets</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\"><br />Description: Use M206 to apply a persistent X Y Z offset to the native home position and coordinate space. This effectively shifts the coordinate space in the negative direction. Used for 3d printing.<br />Usage: M206 [X&lt;offset&gt;] [Y&lt;offset&gt;] [Z&lt;offset&gt;]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">P</span"
                        "><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">arameters:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">[</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">X&lt;offset&gt;] X offset.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-"
                        "content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">[</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">Y&lt;offset&gt;] Y offset.<br />[Z&lt;offset&gt;] Z offset.</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:8pt; color:#212529;\"><br /><br /></span><a name=\"M330\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529;\">M"
                        "</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529;\">330 \342\200\223 Set External Serial Port 1</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\"><br />Description: There are 2 Serial ports on robot for connecting conveyors, slider rail or with external arduino. By default these serials are turned off.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; "
                        "font-size:10pt; color:#212529;\">T</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">o use external Arduino control Delta X, please connect TX RX GND pin at 1 of 2 ports. And send to robot &quot;IsDelta\\n&quot; 2 times to activate the port.</span><a name=\"gcode-content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">W</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">hen connecting Delta X robot with conveyor and slider rail. You can use a computer connected to the robot and control the r"
                        "obot, conveyor, and slider rail through just one COM port on the computer.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">Usage: M330 [R&lt;index&gt;]<br />Parameters:<br /> index =<br />0 : None.<br />1 : Conveyor.<br />2 : Slidingrail.<br /><br /><br /></span><a name=\"M331\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI"
                        ",Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529;\">M</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529;\">331 \342\200\223 Set External Serial Port 2</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\"><br />Description: There are 2 Serial ports on robot for connecting conveyors, slider rail or with external arduino. By default these serials are turned off.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" fon"
                        "t-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">T</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">o use external Arduino control Delta X, please connect TX RX GND pin at 1 of 2 ports. And send to robot &quot;IsDelta\\n&quot; 2 times to activate the port.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">W</span><span style=\" font-family:'-apple-system,Bl"
                        "inkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">hen connecting Delta X robot with conveyor and slider rail. You can use a computer connected to the robot and control the robot, conveyor, and slider rail through just one COM port on the computer.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji"
                        ",Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529;\">Usage: M331 [R&lt;index&gt;]<br />Parameters:<br /> index =<br />0 : None.<br />1 : Conveyor.<br />2 : Slidingrail.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M360\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">360 \342\200\223 Set End effector</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Select the end effector for delta robot.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M360 [E&lt;index&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-si"
                        "ze:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"> index =</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">0 : Vacuum.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">1 : Gripper.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">2 : Pen.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">3 : Laser.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">4 : Printer.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">5 : Custom.</span><span style=\" font-size:10p"
                        "t;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /><br /></span><a name=\"M361\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">361 \342\200\223 Set mm per linear segment</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Set segment length when interpolation.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M361 [P&lt;units&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[P&lt;units&gt;] Segment length when linear interpolatio"
                        "n.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M362\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">362 \342\200\223 Set mm per arc segment</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Set segment length when interpolation.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M361 [P&lt;units&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[P&lt;units&gt;] segment len"
                        "gth when arc interpolation.</span><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"M500\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">500 \342\200\223 Save Settings</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Save all configurable settings to EEPROM.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M500</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M501\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;"
                        "\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">501 \342\200\223 Restore Settings</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Load all saved settings from EEPROM.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M501</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M502\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">502 \342\200\223 Restore Settings</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: Reset all configurable settings to their fact"
                        "ory defaults..</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: M502</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">Conveyor Gcode</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M310\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">310 \342\200\223 Set Speed Mode</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span s"
                        "tyle=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M310 </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[&lt;index&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br /><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">1: Serial Mode.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">2: Volume Mode.</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M311\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span styl"
                        "e=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">311 \342\200\223 Set Speed</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M311 </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[&lt;value&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br />[&lt;value&gt;]: Speed in mm/s<br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M312\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><s"
                        "pan style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">312 - Set Position</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M312 </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[&lt;value&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br />[&lt;value&gt;]: Position in mm</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; ma"
                        "rgin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"M312\"></a><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529; background-color:#ffffff;\">M</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529; background-color:#ffffff;\">313 - Set Speed for Position Moving</span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-rig"
                        "ht:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Description: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Usage: </span><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; font-weight:600; color:#212529; background-color:#ffffff;\">M313 </span><span style=\" font-family:'-apple-system,Blink"
                        "MacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">[&lt;value&gt;] </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Parameters: [&lt;value&gt;]: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji'; font-size:10pt; color:#212529; background-color:#ffffff;\">Speed in mm/s</"
                        "span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">Sliding Rail Gcode</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M320\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">320 \342\200\223 Go To Home</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M320 </span><span s"
                        "tyle=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M321\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">321 - Set Speed</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M321 </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[&lt;value&gt;]</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br />[&lt;va"
                        "lue&gt;]: Speed in mm<br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M322\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">322 \342\200\223 Set Position</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M322 </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">[&lt;</span><span style=\" font-family:'times new roman'; font-size:10pt;\">value</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">&gt;]</span><span style=\" font-siz"
                        "e:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Parameters:</span><span style=\" font-size:10pt;\"><br />[&lt;value&gt;]: Position in mm<br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\"><br /></span><a name=\"M323\"></a><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">323 \342\200\223 Disable Stepper Motor</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Description: .</span><span style=\" font-size:10pt;\"><br /></span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt;\">Usage: </span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">M323</span><span style=\" font-size:10pt;\"><br /><br /><br /></span><a name=\"other\"></a><span style=\" font-"
                        "family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">S</span><span style=\" font-family:'arial,helvetica,sans-serif'; font-size:10pt; font-weight:600;\">ome other commands</span><span style=\" font-size:10pt;\"><br /><br /></span><a name=\"gcode-content\"></a><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">I</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">sDelta</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Confirm the robot<br /><br />Response: \342\200\234</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-style:italic;\">YesDelta</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">\342\200\235<br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">Disconnect</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Disconnect robot<br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">SAVEWIFI</span"
                        "><span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Save wifi information to EEPROM<br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">SAVEIP</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Save delta ip address to EEPROM<br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">IP</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Get the ip address of the robot<br /><br />Response (example): &quot;</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-style:italic;\">192.168.1.199</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">&quot; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"gcode-content\"></a><span style=\" font-family:'Ubuntu'; font-size:11pt;\"><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">gSsid</span>"
                        "<span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Get the ssid of the installed wifi<br /><br />Response (example): &quot;</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-style:italic;\">wifi_imwi</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">&quot;<br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">gPswd</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\"> \342\200\223 Get the password of the installed wifi<br /><br />Response (example): &quot;</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-style:italic;\">matkhauwifi</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">&quot;<br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">SSID:x </span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">\342\200\223 Set SSID of your wifi for the robot<br />          </span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">x</span><span s"
                        "tyle=\" font-family:'Ubuntu'; font-size:11pt;\">: wifi name;<br />Example: &quot;SSID:</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-style:italic;\">wifi_imwi&quot;</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\"><br /><br /></span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">PSWD:x </span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">\342\200\223 Set PASSWORD of your wifi<br />             </span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600;\">x</span><span style=\" font-family:'Ubuntu'; font-size:11pt;\">: password;<br />Example: &quot;PSWD:</span><span style=\" font-family:'Ubuntu'; font-size:11pt; font-style:italic;\">matkhauwifi&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Ubuntu'; font-size:11pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin"
                        "-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.deltaxrobot.com/p/reference.html\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://www.deltaxrobot.com/p/reference.html</span></a></p></body></html>", nullptr));
    } // retranslateUi

};

namespace Ui {
    class GcodeReference: public Ui_GcodeReference {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GCODEREFERENCE_H
