; Generated by Delta X Block Programming
; Delta X 3 adaptation of the 50-cycle subprogram example
robot0 G28
M98 Psend(robot0, "Position", #Cycle.Start, 3000)
M98 Passert(#robot0.HOME_Z < -260, "Unexpected robot Home Z; canceling cycle test")
M98 Passert(#robot0.HOME_Z > -330, "Home Z lacks clearance for the 100 mm cycle depth")
#Counter = 0
FOR #BlockLoop1 = 1 TO 50 STEP 1
    #Counter = #Counter + 1
    robot0 G01 X[#robot0.X] Y[#robot0.Y] Z[#robot0.HOME_Z - 80] W[#robot0.W] F[2000] A[20000]
    robot0 G01 X[-100] Y[#robot0.Y] Z[#robot0.HOME_Z - 80] W[#robot0.W] F[2000] A[20000]
    robot0 G01 X[-100] Y[#robot0.Y] Z[#robot0.HOME_Z - 100] W[#robot0.W] F[2000] A[20000]
    robot0 G01 X[-100] Y[#robot0.Y] Z[#robot0.HOME_Z - 80] W[#robot0.W] F[2000] A[20000]
    robot0 G01 X[100] Y[#robot0.Y] Z[#robot0.HOME_Z - 80] W[#robot0.W] F[2000] A[20000]
    robot0 G01 X[100] Y[#robot0.Y] Z[#robot0.HOME_Z - 100] W[#robot0.W] F[2000] A[20000]
ENDFOR
M98 Passert(#Counter == 50, "Cycle counter did not reach 50")
robot0 G28
M98 PlogMessage("PASS Delta X 50-cycle block program")
