; Generated by Delta X Block Programming
; Connected robot test: lower Z 10 mm and return
M98 Psend(robot0, "Position", #Motion.Start, 3000)
M98 PlogMessage("Starting 10 mm downward Z test")
M98 Passert(#Motion.Start.Z < -295, "Start Z is too close to the upper workspace boundary")
M98 Passert(#Motion.Start.Z > -430, "Start Z lacks clearance for a 10 mm downward test")
robot0 G01 X[#Motion.Start.X] Y[#Motion.Start.Y] Z[#Motion.Start.Z - 10] W[#robot0.W] F[30] A[200]
M98 Pdelay(500)
robot0 G01 X[#Motion.Start.X] Y[#Motion.Start.Y] Z[#Motion.Start.Z] W[#robot0.W] F[30] A[200]
M98 Psend(robot0, "Position", #Motion.End, 3000)
M98 Passert(#abs(#Motion.End.Z - #Motion.Start.Z) < 1, "Robot did not return to the start Z")
M98 PlogMessage("PASS robot 10 mm Z test")
