; Generated by Delta X Block Programming
; Software-only self-test: no device commands
#Blocks.Counter = 0
FOR #BlockLoop1 = 1 TO 3 STEP 1
    #Blocks.Counter = #Blocks.Counter + 1
    M98 PlogMessage("Block iteration")
ENDFOR
M98 Passert(#Blocks.Counter == 3, "Block loop failed")
M98 PwaitUntil(#Blocks.Counter == 3, 200, 10, "Block value was not published")
M98 Pdelay(10)
M98 PlogMessage("PASS block programming")
