; ISOLATED HARNESS ONLY: replaces CloudMapping in the test project.
; The harness uses a temporary directory for the save/load round trip.
M98 Passert(#Examples.Isolated == 1, "Use the isolated command-tour runner")
#Examples.Value = #cloudPointClear()
M98 Passert(#Examples.Value == 1, "clear mapping")
#Examples.Value = #cloudPointAddCalibration(0,0,0,10,20,30,1,"A")
#Examples.Value = #cloudPointAddCalibration(10,0,0,20,20,30,1,"B")
#Examples.Value = #cloudPointAddCalibration(0,10,0,10,30,30,1,"C")
#Examples.Value = #cloudPointAddCalibration(10,10,0,20,30,30,1,"D")
#Examples.Count = #cloudPointGetCount()
M98 Passert(#Examples.Count == 4, "point count")
#Examples.Value = #cloudPointBuildGrid(5)
M98 Passert(#Examples.Value == 1, "build grid")
#Examples.X = #cloudPointTransformX(0,0,0,1)
#Examples.Y = #cloudPointTransformY(0,0,0,1)
#Examples.Z = #cloudPointTransformZ(0,0,0,1)
M98 Passert(#abs(#Examples.X - 10) < 0.01, "mapping X")
M98 Passert(#abs(#Examples.Y - 20) < 0.01, "mapping Y")
M98 Passert(#abs(#Examples.Z - 30) < 0.01, "mapping Z")
#Examples.Confidence = #cloudPointGetConfidence(0,0,0,1)
#Examples.Error = #cloudPointGetError(0,0,0,1)
M98 Passert(#Examples.Confidence > 0, "mapping confidence")
#Examples.Residual = #cloudPointValidate(0.25)
#Examples.Valid = #cloudPointIsValid()
#Examples.Value = #cloudPointSave("tour-mapping.json")
M98 Passert(#Examples.Value == 1, "save")
#Examples.Value = #cloudPointClear()
#Examples.Value = #cloudPointLoad("tour-mapping.json")
M98 Passert(#Examples.Value == 1, "load")
#Examples.Value = #cloudPointExport("Examples.Mapping")
M98 Passert(#Examples.Value == 1, "export")
#Examples.Value = #cloudPointClear()
#Examples.Value = #cloudPointImport("Examples.Mapping")
M98 Passert(#Examples.Value == 1, "import")
#Examples.Value = #cloudPointUpdate(0,0,0,0,10,20,30,0.9)
M98 Passert(#Examples.Value == 1, "update")
#Examples.Value = #cloudPointGetImageX(0)
M98 Passert(#abs(#Examples.Value - 0) < 0.01, "ImageX")
#Examples.Value = #cloudPointGetImageY(0)
M98 Passert(#abs(#Examples.Value - 0) < 0.01, "ImageY")
#Examples.Value = #cloudPointGetImageZ(0)
M98 Passert(#abs(#Examples.Value - 0) < 0.01, "ImageZ")
#Examples.Value = #cloudPointGetRealX(0)
M98 Passert(#abs(#Examples.Value - 10) < 0.01, "RealX")
#Examples.Value = #cloudPointGetRealY(0)
M98 Passert(#abs(#Examples.Value - 20) < 0.01, "RealY")
#Examples.Value = #cloudPointGetRealZ(0)
M98 Passert(#abs(#Examples.Value - 30) < 0.01, "RealZ")
#Examples.Value = #cloudPointGetPointConfidence(0)
M98 Passert(#abs(#Examples.Value - 0.9) < 0.01, "PointConfidence")
#Examples.Value = #cloudPointGetPointError(0)
M98 Passert(#abs(#Examples.Value - 0) < 0.01, "PointError")
#Examples.Value = #cloudPointRemove(3)
M98 Passert(#Examples.Value == 1, "remove")
#Examples.Count = #cloudPointGetCount()
M98 Passert(#Examples.Count == 3, "removed count")
#Examples.CloudPassed = 1
