/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <CameraWidget.h>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include <drawingwidget.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionAdd;
    QAction *actionRemove;
    QAction *actionAbout;
    QAction *actionGcode;
    QAction *actionSoftware;
    QWidget *centralWidget;
    QScrollArea *saProgramFiles;
    QWidget *wgProgramContainer;
    QFrame *frExProgram;
    QLineEdit *leExProgramName;
    QPushButton *pbExDeleteProgram;
    QLabel *lbExGCodeNumber;
    QLabel *lbDebug;
    QPushButton *pbExecuteGcodes;
    QPushButton *pbSaveGcode;
    QPlainTextEdit *pteGcodeArea;
    QLineEdit *leTerminal;
    QPushButton *pbAddGcode;
    QPushButton *pbFormat;
    QPushButton *pbAddNewProgram;
    QTabWidget *twDeltaManager;
    QWidget *tab;
    QWidget *tab_3;
    QTabWidget *tabWidget;
    QWidget *tResultCameraArea;
    CameraWidget *lbScreenStreamer;
    QPushButton *pbLoadCamera;
    QPushButton *pbLoadTestImage;
    QPushButton *pbFilter;
    QLabel *label_11;
    QLineEdit *leFPS;
    QLabel *lbTrackingObject;
    QPushButton *pbObjectRect;
    QPushButton *pbObjectLine;
    QPushButton *pbSwitchWorkFlow;
    QPushButton *pbObjectOrigin;
    QLineEdit *leXRec;
    QLineEdit *leYRec;
    QLineEdit *leRealDistance;
    QLineEdit *leXCoordinate;
    QLineEdit *leYCoordinate;
    QPushButton *pbSelection;
    QLabel *label_12;
    QPushButton *pbChangeXAxis;
    QPushButton *pbClearDetectObjects;
    QWidget *tab_2;
    QLabel *lbImageForDrawing;
    DrawingWidget *lbDrawingArea;
    QWidget *widget_2;
    QLineEdit *leDrawingThreshold;
    QSlider *hsDrawingThreshold;
    QLabel *label_15;
    QWidget *widget_3;
    QLabel *label_17;
    QLabel *label_16;
    QWidget *widget_4;
    QLabel *label_18;
    QLineEdit *leHeightScale;
    QWidget *widget_5;
    QLabel *label_20;
    QLineEdit *leWidthScale;
    QWidget *widget_6;
    QLabel *label_23;
    QLineEdit *lineEdit_11;
    QPushButton *pbSavePicture;
    QPushButton *pbDrawLine;
    QPushButton *pbDrawRectangle;
    QPushButton *pbDrawArc;
    QPushButton *pbDrawCircle;
    QWidget *widget_7;
    QLabel *label_19;
    QLineEdit *leDrawAg1;
    QWidget *widget_8;
    QLabel *label_22;
    QLineEdit *leDrawAg2;
    QWidget *widget_9;
    QLabel *label_24;
    QLineEdit *leDrawAg3;
    QWidget *widget_10;
    QLabel *label_25;
    QLineEdit *leDrawAg4;
    QWidget *widget_11;
    QLabel *label_26;
    QLineEdit *leDrawAg5;
    QPushButton *pbOpenPicture;
    QPushButton *pbDeletePicture;
    QPushButton *pbExportDrawingGcodes;
    QPushButton *pbPainting;
    QComboBox *cbDrawMethod;
    QPushButton *pbZoomIn;
    QPushButton *pbZoomOut;
    QLabel *label_21;
    QPushButton *pbHome;
    QPushButton *pbX;
    QPushButton *pbW;
    QLineEdit *leX;
    QPushButton *pbZ;
    QLineEdit *leY;
    QPushButton *pbGrip;
    QPushButton *pbPump;
    QTabWidget *twDeltaGeometry;
    QWidget *t3D;
    QWidget *wgOpenGl;
    QWidget *t2D;
    QWidget *wg2D;
    QSlider *vsZAdjsution;
    QWidget *tParameter;
    QWidget *widget;
    QLabel *label_9;
    QLabel *label_10;
    QLineEdit *lineEdit_5;
    QLabel *label;
    QLabel *label_6;
    QLabel *label_2;
    QLineEdit *lineEdit_4;
    QLabel *label_5;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_8;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_6;
    QLabel *label_7;
    QPushButton *pbConnect;
    QLineEdit *leZ;
    QLineEdit *leW;
    QPushButton *pbY;
    QPushButton *pbGcodeReference;
    QPushButton *pbSetSpeedConvenyor;
    QLineEdit *leConvenyorSpeed;
    QLineEdit *leCurrentConvenyoPosition;
    QPushButton *pbGetPositionConvenyor;
    QLineEdit *leConvenPosInterval;
    QCheckBox *cbEnoughGetConvenyorContinues;
    QComboBox *cbGcode;
    QLineEdit *leAg1;
    QLabel *lbAg1;
    QLineEdit *leAg2;
    QLabel *lbAg2;
    QLabel *lbAg3;
    QLineEdit *leAg3;
    QLabel *lbAg4;
    QLineEdit *leAg4;
    QLabel *lbAg5;
    QLineEdit *leAg5;
    QLineEdit *leAg6;
    QLabel *lbAg6;
    QLineEdit *leVariable3;
    QLineEdit *leVariable2;
    QLabel *lbVar3;
    QLabel *lbVar1;
    QLabel *lbVar2;
    QLineEdit *leVariable3_2;
    QLineEdit *leVariable1;
    QLabel *lbVar3_2;
    QLabel *lbVar1_2;
    QLabel *lbVar3_3;
    QLineEdit *leVariable3_3;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuHelp;
    QMenu *menuReferences;
    QMenu *menuEditor;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1299, 688);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        QIcon icon;
        icon.addFile(QStringLiteral("icon/logo.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setStyleSheet(QStringLiteral(""));
        actionAdd = new QAction(MainWindow);
        actionAdd->setObjectName(QStringLiteral("actionAdd"));
        actionRemove = new QAction(MainWindow);
        actionRemove->setObjectName(QStringLiteral("actionRemove"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionGcode = new QAction(MainWindow);
        actionGcode->setObjectName(QStringLiteral("actionGcode"));
        actionSoftware = new QAction(MainWindow);
        actionSoftware->setObjectName(QStringLiteral("actionSoftware"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        saProgramFiles = new QScrollArea(centralWidget);
        saProgramFiles->setObjectName(QStringLiteral("saProgramFiles"));
        saProgramFiles->setEnabled(true);
        saProgramFiles->setGeometry(QRect(970, 471, 251, 160));
        saProgramFiles->setMinimumSize(QSize(251, 160));
        saProgramFiles->setStyleSheet(QStringLiteral(""));
        saProgramFiles->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        saProgramFiles->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        saProgramFiles->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        saProgramFiles->setWidgetResizable(false);
        wgProgramContainer = new QWidget();
        wgProgramContainer->setObjectName(QStringLiteral("wgProgramContainer"));
        wgProgramContainer->setGeometry(QRect(0, 0, 279, 589));
        frExProgram = new QFrame(wgProgramContainer);
        frExProgram->setObjectName(QStringLiteral("frExProgram"));
        frExProgram->setGeometry(QRect(10, 10, 221, 71));
        frExProgram->setStyleSheet(QStringLiteral("background-color:rgb(209, 209, 209)"));
        frExProgram->setFrameShape(QFrame::StyledPanel);
        frExProgram->setFrameShadow(QFrame::Raised);
        leExProgramName = new QLineEdit(frExProgram);
        leExProgramName->setObjectName(QStringLiteral("leExProgramName"));
        leExProgramName->setEnabled(true);
        leExProgramName->setGeometry(QRect(10, 10, 160, 30));
        QFont font;
        font.setPointSize(10);
        leExProgramName->setFont(font);
        leExProgramName->setCursor(QCursor(Qt::SizeHorCursor));
        leExProgramName->setStyleSheet(QStringLiteral(""));
        pbExDeleteProgram = new QPushButton(frExProgram);
        pbExDeleteProgram->setObjectName(QStringLiteral("pbExDeleteProgram"));
        pbExDeleteProgram->setGeometry(QRect(180, 10, 30, 31));
        QIcon icon1;
        icon1.addFile(QStringLiteral("icon/delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbExDeleteProgram->setIcon(icon1);
        pbExDeleteProgram->setIconSize(QSize(30, 30));
        pbExDeleteProgram->setAutoDefault(false);
        pbExDeleteProgram->setFlat(true);
        lbExGCodeNumber = new QLabel(frExProgram);
        lbExGCodeNumber->setObjectName(QStringLiteral("lbExGCodeNumber"));
        lbExGCodeNumber->setGeometry(QRect(10, 50, 101, 16));
        saProgramFiles->setWidget(wgProgramContainer);
        lbDebug = new QLabel(centralWidget);
        lbDebug->setObjectName(QStringLiteral("lbDebug"));
        lbDebug->setGeometry(QRect(10, 640, 1281, 21));
        lbDebug->setStyleSheet(QLatin1String("background-color:rgb(70, 70, 70);\n"
"color:rgb(0, 235, 0);\n"
""));
        pbExecuteGcodes = new QPushButton(centralWidget);
        pbExecuteGcodes->setObjectName(QStringLiteral("pbExecuteGcodes"));
        pbExecuteGcodes->setGeometry(QRect(970, 10, 35, 35));
        pbExecuteGcodes->setAutoFillBackground(false);
        QIcon icon2;
        icon2.addFile(QStringLiteral("icon/play.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon2.addFile(QStringLiteral("icon/stop.png"), QSize(), QIcon::Normal, QIcon::On);
        pbExecuteGcodes->setIcon(icon2);
        pbExecuteGcodes->setIconSize(QSize(30, 30));
        pbExecuteGcodes->setCheckable(true);
        pbExecuteGcodes->setFlat(false);
        pbSaveGcode = new QPushButton(centralWidget);
        pbSaveGcode->setObjectName(QStringLiteral("pbSaveGcode"));
        pbSaveGcode->setGeometry(QRect(1010, 10, 35, 35));
        QIcon icon3;
        icon3.addFile(QStringLiteral("icon/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbSaveGcode->setIcon(icon3);
        pbSaveGcode->setIconSize(QSize(30, 30));
        pteGcodeArea = new QPlainTextEdit(centralWidget);
        pteGcodeArea->setObjectName(QStringLiteral("pteGcodeArea"));
        pteGcodeArea->setGeometry(QRect(970, 160, 321, 300));
        pteGcodeArea->setMinimumSize(QSize(321, 300));
        QFont font1;
        font1.setPointSize(9);
        pteGcodeArea->setFont(font1);
        pteGcodeArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        leTerminal = new QLineEdit(centralWidget);
        leTerminal->setObjectName(QStringLiteral("leTerminal"));
        leTerminal->setGeometry(QRect(10, 660, 1281, 22));
        pbAddGcode = new QPushButton(centralWidget);
        pbAddGcode->setObjectName(QStringLiteral("pbAddGcode"));
        pbAddGcode->setGeometry(QRect(1175, 10, 81, 35));
        pbAddGcode->setAutoDefault(false);
        pbAddGcode->setFlat(false);
        pbFormat = new QPushButton(centralWidget);
        pbFormat->setObjectName(QStringLiteral("pbFormat"));
        pbFormat->setGeometry(QRect(1050, 10, 35, 35));
        QIcon icon4;
        icon4.addFile(QStringLiteral("icon/index.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbFormat->setIcon(icon4);
        pbFormat->setIconSize(QSize(30, 30));
        pbAddNewProgram = new QPushButton(centralWidget);
        pbAddNewProgram->setObjectName(QStringLiteral("pbAddNewProgram"));
        pbAddNewProgram->setGeometry(QRect(1230, 470, 61, 31));
        QIcon icon5;
        icon5.addFile(QStringLiteral("icon/new.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbAddNewProgram->setIcon(icon5);
        pbAddNewProgram->setIconSize(QSize(16, 16));
        pbAddNewProgram->setFlat(false);
        twDeltaManager = new QTabWidget(centralWidget);
        twDeltaManager->setObjectName(QStringLiteral("twDeltaManager"));
        twDeltaManager->setGeometry(QRect(0, 0, 521, 28));
        QFont font2;
        font2.setPointSize(12);
        twDeltaManager->setFont(font2);
        twDeltaManager->setStyleSheet(QStringLiteral("color: rgb(18, 190, 190);"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        twDeltaManager->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        twDeltaManager->addTab(tab_3, QString());
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(530, 110, 431, 521));
        tResultCameraArea = new QWidget();
        tResultCameraArea->setObjectName(QStringLiteral("tResultCameraArea"));
        lbScreenStreamer = new CameraWidget(tResultCameraArea);
        lbScreenStreamer->setObjectName(QStringLiteral("lbScreenStreamer"));
        lbScreenStreamer->setGeometry(QRect(10, 180, 401, 301));
        lbScreenStreamer->setStyleSheet(QStringLiteral("background-color:rgb(230, 230, 230)"));
        lbScreenStreamer->setScaledContents(false);
        lbScreenStreamer->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        pbLoadCamera = new QPushButton(tResultCameraArea);
        pbLoadCamera->setObjectName(QStringLiteral("pbLoadCamera"));
        pbLoadCamera->setGeometry(QRect(10, 10, 41, 21));
        QIcon icon6;
        icon6.addFile(QStringLiteral("icon/webcam.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon6.addFile(QStringLiteral("icon/stop.png"), QSize(), QIcon::Normal, QIcon::On);
        pbLoadCamera->setIcon(icon6);
        pbLoadCamera->setCheckable(true);
        pbLoadTestImage = new QPushButton(tResultCameraArea);
        pbLoadTestImage->setObjectName(QStringLiteral("pbLoadTestImage"));
        pbLoadTestImage->setGeometry(QRect(60, 10, 41, 21));
        QIcon icon7;
        icon7.addFile(QStringLiteral("icon/image.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbLoadTestImage->setIcon(icon7);
        pbFilter = new QPushButton(tResultCameraArea);
        pbFilter->setObjectName(QStringLiteral("pbFilter"));
        pbFilter->setGeometry(QRect(10, 150, 41, 21));
        QIcon icon8;
        icon8.addFile(QStringLiteral("icon/Slider 2_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbFilter->setIcon(icon8);
        label_11 = new QLabel(tResultCameraArea);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(380, 140, 31, 16));
        leFPS = new QLineEdit(tResultCameraArea);
        leFPS->setObjectName(QStringLiteral("leFPS"));
        leFPS->setGeometry(QRect(300, 140, 71, 22));
        leFPS->setAlignment(Qt::AlignCenter);
        lbTrackingObject = new QLabel(tResultCameraArea);
        lbTrackingObject->setObjectName(QStringLiteral("lbTrackingObject"));
        lbTrackingObject->setGeometry(QRect(10, 40, 91, 101));
        lbTrackingObject->setStyleSheet(QStringLiteral("background-color:rgb(230, 230, 230)"));
        pbObjectRect = new QPushButton(tResultCameraArea);
        pbObjectRect->setObjectName(QStringLiteral("pbObjectRect"));
        pbObjectRect->setGeometry(QRect(300, 50, 31, 28));
        pbObjectRect->setStyleSheet(QStringLiteral(""));
        QIcon icon9;
        icon9.addFile(QStringLiteral("icon/Rectangle_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbObjectRect->setIcon(icon9);
        pbObjectLine = new QPushButton(tResultCameraArea);
        pbObjectLine->setObjectName(QStringLiteral("pbObjectLine"));
        pbObjectLine->setGeometry(QRect(300, 80, 31, 28));
        QIcon icon10;
        icon10.addFile(QStringLiteral("icon/Width_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbObjectLine->setIcon(icon10);
        pbSwitchWorkFlow = new QPushButton(tResultCameraArea);
        pbSwitchWorkFlow->setObjectName(QStringLiteral("pbSwitchWorkFlow"));
        pbSwitchWorkFlow->setGeometry(QRect(60, 150, 41, 21));
        QIcon icon11;
        icon11.addFile(QStringLiteral("icon/Workflow_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbSwitchWorkFlow->setIcon(icon11);
        pbObjectOrigin = new QPushButton(tResultCameraArea);
        pbObjectOrigin->setObjectName(QStringLiteral("pbObjectOrigin"));
        pbObjectOrigin->setGeometry(QRect(300, 110, 31, 28));
        QIcon icon12;
        icon12.addFile(QStringLiteral("icon/Scatter Plot_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbObjectOrigin->setIcon(icon12);
        leXRec = new QLineEdit(tResultCameraArea);
        leXRec->setObjectName(QStringLiteral("leXRec"));
        leXRec->setGeometry(QRect(340, 50, 31, 22));
        leYRec = new QLineEdit(tResultCameraArea);
        leYRec->setObjectName(QStringLiteral("leYRec"));
        leYRec->setGeometry(QRect(380, 50, 31, 22));
        leRealDistance = new QLineEdit(tResultCameraArea);
        leRealDistance->setObjectName(QStringLiteral("leRealDistance"));
        leRealDistance->setGeometry(QRect(340, 80, 31, 22));
        leXCoordinate = new QLineEdit(tResultCameraArea);
        leXCoordinate->setObjectName(QStringLiteral("leXCoordinate"));
        leXCoordinate->setGeometry(QRect(340, 110, 31, 22));
        leYCoordinate = new QLineEdit(tResultCameraArea);
        leYCoordinate->setObjectName(QStringLiteral("leYCoordinate"));
        leYCoordinate->setGeometry(QRect(380, 110, 31, 22));
        pbSelection = new QPushButton(tResultCameraArea);
        pbSelection->setObjectName(QStringLiteral("pbSelection"));
        pbSelection->setGeometry(QRect(300, 20, 111, 28));
        QIcon icon13;
        icon13.addFile(QStringLiteral("icon/Cursor_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbSelection->setIcon(icon13);
        label_12 = new QLabel(tResultCameraArea);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(386, 82, 21, 16));
        pbChangeXAxis = new QPushButton(tResultCameraArea);
        pbChangeXAxis->setObjectName(QStringLiteral("pbChangeXAxis"));
        pbChangeXAxis->setGeometry(QRect(110, 150, 41, 21));
        QIcon icon14;
        icon14.addFile(QStringLiteral("icon/Arrow Pointing Down_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon14.addFile(QStringLiteral("icon/Right Arrow_16px.png"), QSize(), QIcon::Normal, QIcon::On);
        pbChangeXAxis->setIcon(icon14);
        pbChangeXAxis->setCheckable(true);
        pbClearDetectObjects = new QPushButton(tResultCameraArea);
        pbClearDetectObjects->setObjectName(QStringLiteral("pbClearDetectObjects"));
        pbClearDetectObjects->setGeometry(QRect(160, 150, 41, 21));
        QIcon icon15;
        icon15.addFile(QStringLiteral("icon/Eraser_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbClearDetectObjects->setIcon(icon15);
        tabWidget->addTab(tResultCameraArea, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        lbImageForDrawing = new QLabel(tab_2);
        lbImageForDrawing->setObjectName(QStringLiteral("lbImageForDrawing"));
        lbImageForDrawing->setGeometry(QRect(10, 10, 208, 117));
        lbImageForDrawing->setStyleSheet(QStringLiteral("background-color: rgb(142, 254, 255);"));
        lbDrawingArea = new DrawingWidget(tab_2);
        lbDrawingArea->setObjectName(QStringLiteral("lbDrawingArea"));
        lbDrawingArea->setGeometry(QRect(10, 136, 350, 350));
        lbDrawingArea->setStyleSheet(QStringLiteral("background-color: rgb(142, 254, 255);"));
        widget_2 = new QWidget(tab_2);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(299, 10, 121, 57));
        widget_2->setStyleSheet(QStringLiteral("background-color: rgb(171, 225, 224);"));
        leDrawingThreshold = new QLineEdit(widget_2);
        leDrawingThreshold->setObjectName(QStringLiteral("leDrawingThreshold"));
        leDrawingThreshold->setGeometry(QRect(80, 4, 35, 22));
        hsDrawingThreshold = new QSlider(widget_2);
        hsDrawingThreshold->setObjectName(QStringLiteral("hsDrawingThreshold"));
        hsDrawingThreshold->setGeometry(QRect(7, 28, 107, 22));
        hsDrawingThreshold->setMaximum(255);
        hsDrawingThreshold->setValue(150);
        hsDrawingThreshold->setOrientation(Qt::Horizontal);
        label_15 = new QLabel(widget_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 6, 59, 16));
        widget_3 = new QWidget(tab_2);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(226, 34, 63, 33));
        widget_3->setStyleSheet(QStringLiteral("background-color: rgb(221, 221, 221);"));
        label_17 = new QLabel(widget_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 0, 49, 16));
        QFont font3;
        font3.setPointSize(7);
        label_17->setFont(font3);
        label_17->setStyleSheet(QStringLiteral(""));
        label_16 = new QLabel(widget_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 14, 47, 17));
        label_16->setFont(font3);
        label_16->setStyleSheet(QStringLiteral(""));
        widget_4 = new QWidget(tab_2);
        widget_4->setObjectName(QStringLiteral("widget_4"));
        widget_4->setGeometry(QRect(224, 74, 43, 53));
        widget_4->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_18 = new QLabel(widget_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(4, 4, 49, 16));
        QFont font4;
        font4.setPointSize(6);
        label_18->setFont(font4);
        leHeightScale = new QLineEdit(widget_4);
        leHeightScale->setObjectName(QStringLiteral("leHeightScale"));
        leHeightScale->setGeometry(QRect(4, 26, 35, 22));
        widget_5 = new QWidget(tab_2);
        widget_5->setObjectName(QStringLiteral("widget_5"));
        widget_5->setGeometry(QRect(270, 74, 43, 53));
        widget_5->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_20 = new QLabel(widget_5);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(4, 4, 37, 16));
        label_20->setFont(font4);
        leWidthScale = new QLineEdit(widget_5);
        leWidthScale->setObjectName(QStringLiteral("leWidthScale"));
        leWidthScale->setGeometry(QRect(4, 26, 35, 22));
        widget_6 = new QWidget(tab_2);
        widget_6->setObjectName(QStringLiteral("widget_6"));
        widget_6->setGeometry(QRect(316, 74, 39, 53));
        widget_6->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_23 = new QLabel(widget_6);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(2, 4, 35, 16));
        label_23->setAlignment(Qt::AlignCenter);
        lineEdit_11 = new QLineEdit(widget_6);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(4, 26, 31, 22));
        pbSavePicture = new QPushButton(tab_2);
        pbSavePicture->setObjectName(QStringLiteral("pbSavePicture"));
        pbSavePicture->setGeometry(QRect(358, 102, 30, 25));
        QIcon icon16;
        icon16.addFile(QStringLiteral("icon/Save_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbSavePicture->setIcon(icon16);
        pbDrawLine = new QPushButton(tab_2);
        pbDrawLine->setObjectName(QStringLiteral("pbDrawLine"));
        pbDrawLine->setGeometry(QRect(364, 316, 28, 28));
        QIcon icon17;
        icon17.addFile(QStringLiteral("icon/Line_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbDrawLine->setIcon(icon17);
        pbDrawRectangle = new QPushButton(tab_2);
        pbDrawRectangle->setObjectName(QStringLiteral("pbDrawRectangle"));
        pbDrawRectangle->setGeometry(QRect(394, 316, 28, 28));
        QIcon icon18;
        icon18.addFile(QStringLiteral("icon/Rectangular_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbDrawRectangle->setIcon(icon18);
        pbDrawArc = new QPushButton(tab_2);
        pbDrawArc->setObjectName(QStringLiteral("pbDrawArc"));
        pbDrawArc->setGeometry(QRect(364, 348, 28, 28));
        QIcon icon19;
        icon19.addFile(QStringLiteral("icon/Circled Notch_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbDrawArc->setIcon(icon19);
        pbDrawCircle = new QPushButton(tab_2);
        pbDrawCircle->setObjectName(QStringLiteral("pbDrawCircle"));
        pbDrawCircle->setGeometry(QRect(394, 348, 28, 28));
        QIcon icon20;
        icon20.addFile(QStringLiteral("icon/Circle_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbDrawCircle->setIcon(icon20);
        widget_7 = new QWidget(tab_2);
        widget_7->setObjectName(QStringLiteral("widget_7"));
        widget_7->setGeometry(QRect(366, 136, 53, 31));
        widget_7->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_19 = new QLabel(widget_7);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(6, 8, 16, 16));
        leDrawAg1 = new QLineEdit(widget_7);
        leDrawAg1->setObjectName(QStringLiteral("leDrawAg1"));
        leDrawAg1->setGeometry(QRect(16, 6, 33, 22));
        widget_8 = new QWidget(tab_2);
        widget_8->setObjectName(QStringLiteral("widget_8"));
        widget_8->setGeometry(QRect(366, 170, 53, 31));
        widget_8->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_22 = new QLabel(widget_8);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(6, 8, 16, 16));
        leDrawAg2 = new QLineEdit(widget_8);
        leDrawAg2->setObjectName(QStringLiteral("leDrawAg2"));
        leDrawAg2->setGeometry(QRect(16, 6, 33, 22));
        widget_9 = new QWidget(tab_2);
        widget_9->setObjectName(QStringLiteral("widget_9"));
        widget_9->setGeometry(QRect(366, 204, 53, 31));
        widget_9->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_24 = new QLabel(widget_9);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(6, 8, 16, 16));
        leDrawAg3 = new QLineEdit(widget_9);
        leDrawAg3->setObjectName(QStringLiteral("leDrawAg3"));
        leDrawAg3->setGeometry(QRect(16, 6, 33, 22));
        widget_10 = new QWidget(tab_2);
        widget_10->setObjectName(QStringLiteral("widget_10"));
        widget_10->setGeometry(QRect(366, 238, 53, 31));
        widget_10->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_25 = new QLabel(widget_10);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(2, 8, 16, 16));
        QFont font5;
        font5.setPointSize(8);
        label_25->setFont(font5);
        leDrawAg4 = new QLineEdit(widget_10);
        leDrawAg4->setObjectName(QStringLiteral("leDrawAg4"));
        leDrawAg4->setGeometry(QRect(16, 6, 33, 22));
        widget_11 = new QWidget(tab_2);
        widget_11->setObjectName(QStringLiteral("widget_11"));
        widget_11->setGeometry(QRect(366, 272, 53, 31));
        widget_11->setStyleSheet(QStringLiteral("background-color: rgb(234, 234, 234);"));
        label_26 = new QLabel(widget_11);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(6, 8, 16, 16));
        leDrawAg5 = new QLineEdit(widget_11);
        leDrawAg5->setObjectName(QStringLiteral("leDrawAg5"));
        leDrawAg5->setGeometry(QRect(16, 6, 33, 22));
        pbOpenPicture = new QPushButton(tab_2);
        pbOpenPicture->setObjectName(QStringLiteral("pbOpenPicture"));
        pbOpenPicture->setGeometry(QRect(224, 10, 29, 21));
        QIcon icon21;
        icon21.addFile(QStringLiteral("icon/Full Image_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbOpenPicture->setIcon(icon21);
        pbDeletePicture = new QPushButton(tab_2);
        pbDeletePicture->setObjectName(QStringLiteral("pbDeletePicture"));
        pbDeletePicture->setGeometry(QRect(262, 10, 29, 21));
        QIcon icon22;
        icon22.addFile(QStringLiteral("icon/Trash_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbDeletePicture->setIcon(icon22);
        pbExportDrawingGcodes = new QPushButton(tab_2);
        pbExportDrawingGcodes->setObjectName(QStringLiteral("pbExportDrawingGcodes"));
        pbExportDrawingGcodes->setGeometry(QRect(364, 448, 59, 39));
        pbPainting = new QPushButton(tab_2);
        pbPainting->setObjectName(QStringLiteral("pbPainting"));
        pbPainting->setGeometry(QRect(390, 102, 30, 25));
        QIcon icon23;
        icon23.addFile(QStringLiteral("icon/Paint_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbPainting->setIcon(icon23);
        cbDrawMethod = new QComboBox(tab_2);
        cbDrawMethod->setObjectName(QStringLiteral("cbDrawMethod"));
        cbDrawMethod->setGeometry(QRect(360, 74, 59, 22));
        pbZoomIn = new QPushButton(tab_2);
        pbZoomIn->setObjectName(QStringLiteral("pbZoomIn"));
        pbZoomIn->setGeometry(QRect(364, 380, 28, 28));
        QIcon icon24;
        icon24.addFile(QStringLiteral("icon/Zoom In_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbZoomIn->setIcon(icon24);
        pbZoomOut = new QPushButton(tab_2);
        pbZoomOut->setObjectName(QStringLiteral("pbZoomOut"));
        pbZoomOut->setGeometry(QRect(394, 380, 28, 28));
        QIcon icon25;
        icon25.addFile(QStringLiteral("icon/Zoom Out_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbZoomOut->setIcon(icon25);
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(316, 466, 39, 16));
        tabWidget->addTab(tab_2, QString());
        pbHome = new QPushButton(centralWidget);
        pbHome->setObjectName(QStringLiteral("pbHome"));
        pbHome->setGeometry(QRect(200, 40, 51, 61));
        QIcon icon26;
        icon26.addFile(QStringLiteral("icon/home.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbHome->setIcon(icon26);
        pbHome->setIconSize(QSize(30, 30));
        pbX = new QPushButton(centralWidget);
        pbX->setObjectName(QStringLiteral("pbX"));
        pbX->setGeometry(QRect(260, 40, 41, 27));
        pbW = new QPushButton(centralWidget);
        pbW->setObjectName(QStringLiteral("pbW"));
        pbW->setGeometry(QRect(410, 40, 41, 27));
        leX = new QLineEdit(centralWidget);
        leX->setObjectName(QStringLiteral("leX"));
        leX->setGeometry(QRect(260, 70, 41, 27));
        pbZ = new QPushButton(centralWidget);
        pbZ->setObjectName(QStringLiteral("pbZ"));
        pbZ->setGeometry(QRect(360, 40, 41, 27));
        leY = new QLineEdit(centralWidget);
        leY->setObjectName(QStringLiteral("leY"));
        leY->setGeometry(QRect(310, 70, 41, 27));
        pbGrip = new QPushButton(centralWidget);
        pbGrip->setObjectName(QStringLiteral("pbGrip"));
        pbGrip->setGeometry(QRect(460, 40, 61, 27));
        pbGrip->setAutoFillBackground(false);
        pbGrip->setAutoDefault(false);
        pbGrip->setFlat(false);
        pbPump = new QPushButton(centralWidget);
        pbPump->setObjectName(QStringLiteral("pbPump"));
        pbPump->setGeometry(QRect(460, 70, 61, 27));
        pbPump->setAutoFillBackground(false);
        QIcon icon27;
        icon27.addFile(QStringLiteral("icon/Toggle Off_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon27.addFile(QStringLiteral("icon/Toggle On_16px.png"), QSize(), QIcon::Normal, QIcon::On);
        pbPump->setIcon(icon27);
        pbPump->setCheckable(true);
        pbPump->setAutoDefault(false);
        pbPump->setFlat(false);
        twDeltaGeometry = new QTabWidget(centralWidget);
        twDeltaGeometry->setObjectName(QStringLiteral("twDeltaGeometry"));
        twDeltaGeometry->setGeometry(QRect(0, 90, 521, 541));
        t3D = new QWidget();
        t3D->setObjectName(QStringLiteral("t3D"));
        wgOpenGl = new QWidget(t3D);
        wgOpenGl->setObjectName(QStringLiteral("wgOpenGl"));
        wgOpenGl->setGeometry(QRect(0, 0, 500, 500));
        wgOpenGl->setStyleSheet(QStringLiteral("background-color: rgb(209, 209, 209);"));
        twDeltaGeometry->addTab(t3D, QString());
        t2D = new QWidget();
        t2D->setObjectName(QStringLiteral("t2D"));
        wg2D = new QWidget(t2D);
        wg2D->setObjectName(QStringLiteral("wg2D"));
        wg2D->setGeometry(QRect(50, 10, 300, 300));
        wg2D->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        vsZAdjsution = new QSlider(t2D);
        vsZAdjsution->setObjectName(QStringLiteral("vsZAdjsution"));
        vsZAdjsution->setGeometry(QRect(10, 9, 22, 301));
        vsZAdjsution->setMaximum(300);
        vsZAdjsution->setOrientation(Qt::Vertical);
        twDeltaGeometry->addTab(t2D, QString());
        tParameter = new QWidget();
        tParameter->setObjectName(QStringLiteral("tParameter"));
        widget = new QWidget(tParameter);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(0, 10, 381, 301));
        label_9 = new QLabel(widget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(120, 130, 41, 20));
        label_9->setFont(font2);
        label_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_10 = new QLabel(widget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 130, 21, 20));
        label_10->setFont(font2);
        label_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_5 = new QLineEdit(widget);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(40, 40, 81, 22));
        label = new QLabel(widget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 21, 20));
        label->setFont(font2);
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_6 = new QLabel(widget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 70, 21, 20));
        label_6->setFont(font2);
        label_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2 = new QLabel(widget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(120, 10, 41, 20));
        label_2->setFont(font2);
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_4 = new QLineEdit(widget);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(40, 10, 81, 22));
        label_5 = new QLabel(widget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(120, 70, 41, 20));
        label_5->setFont(font2);
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_3 = new QLabel(widget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 40, 21, 20));
        label_3->setFont(font2);
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_4 = new QLabel(widget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(120, 40, 41, 20));
        label_4->setFont(font2);
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_8 = new QLabel(widget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(120, 100, 41, 20));
        label_8->setFont(font2);
        label_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_7 = new QLineEdit(widget);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(40, 100, 81, 22));
        lineEdit_8 = new QLineEdit(widget);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(40, 130, 81, 22));
        lineEdit_6 = new QLineEdit(widget);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(40, 70, 81, 22));
        label_7 = new QLabel(widget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 100, 21, 20));
        label_7->setFont(font2);
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        twDeltaGeometry->addTab(tParameter, QString());
        pbConnect = new QPushButton(centralWidget);
        pbConnect->setObjectName(QStringLiteral("pbConnect"));
        pbConnect->setGeometry(QRect(0, 40, 101, 41));
        pbConnect->setStyleSheet(QLatin1String("background-color: rgb(30, 88, 180);\n"
"color: rgb(255, 255, 255);"));
        QIcon icon28;
        icon28.addFile(QStringLiteral("icon/disconnected.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon28.addFile(QStringLiteral("icon/connected.png"), QSize(), QIcon::Normal, QIcon::On);
        pbConnect->setIcon(icon28);
        pbConnect->setIconSize(QSize(30, 20));
        leZ = new QLineEdit(centralWidget);
        leZ->setObjectName(QStringLiteral("leZ"));
        leZ->setGeometry(QRect(360, 70, 41, 27));
        leW = new QLineEdit(centralWidget);
        leW->setObjectName(QStringLiteral("leW"));
        leW->setGeometry(QRect(410, 70, 41, 27));
        pbY = new QPushButton(centralWidget);
        pbY->setObjectName(QStringLiteral("pbY"));
        pbY->setGeometry(QRect(310, 40, 41, 27));
        pbGcodeReference = new QPushButton(centralWidget);
        pbGcodeReference->setObjectName(QStringLiteral("pbGcodeReference"));
        pbGcodeReference->setGeometry(QRect(1260, 10, 35, 35));
        QIcon icon29;
        icon29.addFile(QStringLiteral("icon/Help_16px.png"), QSize(), QIcon::Normal, QIcon::Off);
        pbGcodeReference->setIcon(icon29);
        pbSetSpeedConvenyor = new QPushButton(centralWidget);
        pbSetSpeedConvenyor->setObjectName(QStringLiteral("pbSetSpeedConvenyor"));
        pbSetSpeedConvenyor->setGeometry(QRect(530, 40, 61, 27));
        leConvenyorSpeed = new QLineEdit(centralWidget);
        leConvenyorSpeed->setObjectName(QStringLiteral("leConvenyorSpeed"));
        leConvenyorSpeed->setGeometry(QRect(530, 70, 61, 27));
        leCurrentConvenyoPosition = new QLineEdit(centralWidget);
        leCurrentConvenyoPosition->setObjectName(QStringLiteral("leCurrentConvenyoPosition"));
        leCurrentConvenyoPosition->setGeometry(QRect(600, 70, 71, 27));
        leCurrentConvenyoPosition->setReadOnly(true);
        pbGetPositionConvenyor = new QPushButton(centralWidget);
        pbGetPositionConvenyor->setObjectName(QStringLiteral("pbGetPositionConvenyor"));
        pbGetPositionConvenyor->setGeometry(QRect(600, 40, 71, 27));
        leConvenPosInterval = new QLineEdit(centralWidget);
        leConvenPosInterval->setObjectName(QStringLiteral("leConvenPosInterval"));
        leConvenPosInterval->setGeometry(QRect(680, 70, 51, 27));
        leConvenPosInterval->setReadOnly(false);
        cbEnoughGetConvenyorContinues = new QCheckBox(centralWidget);
        cbEnoughGetConvenyorContinues->setObjectName(QStringLiteral("cbEnoughGetConvenyorContinues"));
        cbEnoughGetConvenyorContinues->setGeometry(QRect(680, 40, 51, 20));
        cbGcode = new QComboBox(centralWidget);
        cbGcode->setObjectName(QStringLiteral("cbGcode"));
        cbGcode->setGeometry(QRect(1100, 10, 71, 35));
        leAg1 = new QLineEdit(centralWidget);
        leAg1->setObjectName(QStringLiteral("leAg1"));
        leAg1->setGeometry(QRect(990, 55, 30, 27));
        leAg1->setReadOnly(false);
        lbAg1 = new QLabel(centralWidget);
        lbAg1->setObjectName(QStringLiteral("lbAg1"));
        lbAg1->setGeometry(QRect(974, 60, 16, 20));
        lbAg1->setStyleSheet(QStringLiteral("background-color: rgb(124, 221, 235);"));
        lbAg1->setAlignment(Qt::AlignCenter);
        leAg2 = new QLineEdit(centralWidget);
        leAg2->setObjectName(QStringLiteral("leAg2"));
        leAg2->setGeometry(QRect(1043, 55, 30, 27));
        leAg2->setReadOnly(false);
        lbAg2 = new QLabel(centralWidget);
        lbAg2->setObjectName(QStringLiteral("lbAg2"));
        lbAg2->setGeometry(QRect(1027, 60, 16, 20));
        lbAg2->setStyleSheet(QStringLiteral("background-color: rgb(124, 221, 235);"));
        lbAg2->setAlignment(Qt::AlignCenter);
        lbAg3 = new QLabel(centralWidget);
        lbAg3->setObjectName(QStringLiteral("lbAg3"));
        lbAg3->setGeometry(QRect(1081, 60, 16, 20));
        lbAg3->setStyleSheet(QStringLiteral("background-color: rgb(124, 221, 235);"));
        lbAg3->setAlignment(Qt::AlignCenter);
        leAg3 = new QLineEdit(centralWidget);
        leAg3->setObjectName(QStringLiteral("leAg3"));
        leAg3->setGeometry(QRect(1097, 55, 30, 27));
        leAg3->setReadOnly(false);
        lbAg4 = new QLabel(centralWidget);
        lbAg4->setObjectName(QStringLiteral("lbAg4"));
        lbAg4->setGeometry(QRect(1135, 60, 16, 20));
        lbAg4->setStyleSheet(QStringLiteral("background-color: rgb(124, 221, 235);"));
        lbAg4->setAlignment(Qt::AlignCenter);
        leAg4 = new QLineEdit(centralWidget);
        leAg4->setObjectName(QStringLiteral("leAg4"));
        leAg4->setGeometry(QRect(1152, 55, 30, 27));
        leAg4->setReadOnly(false);
        lbAg5 = new QLabel(centralWidget);
        lbAg5->setObjectName(QStringLiteral("lbAg5"));
        lbAg5->setGeometry(QRect(1190, 60, 16, 20));
        lbAg5->setStyleSheet(QStringLiteral("background-color: rgb(124, 221, 235);"));
        lbAg5->setAlignment(Qt::AlignCenter);
        leAg5 = new QLineEdit(centralWidget);
        leAg5->setObjectName(QStringLiteral("leAg5"));
        leAg5->setGeometry(QRect(1205, 55, 30, 27));
        leAg5->setReadOnly(false);
        leAg6 = new QLineEdit(centralWidget);
        leAg6->setObjectName(QStringLiteral("leAg6"));
        leAg6->setGeometry(QRect(1260, 55, 30, 27));
        leAg6->setReadOnly(false);
        lbAg6 = new QLabel(centralWidget);
        lbAg6->setObjectName(QStringLiteral("lbAg6"));
        lbAg6->setGeometry(QRect(1242, 60, 16, 20));
        lbAg6->setStyleSheet(QStringLiteral("background-color: rgb(124, 221, 235);"));
        leVariable3 = new QLineEdit(centralWidget);
        leVariable3->setObjectName(QStringLiteral("leVariable3"));
        leVariable3->setGeometry(QRect(1151, 100, 41, 22));
        leVariable2 = new QLineEdit(centralWidget);
        leVariable2->setObjectName(QStringLiteral("leVariable2"));
        leVariable2->setGeometry(QRect(1101, 100, 41, 22));
        lbVar3 = new QLabel(centralWidget);
        lbVar3->setObjectName(QStringLiteral("lbVar3"));
        lbVar3->setGeometry(QRect(1151, 130, 41, 20));
        lbVar3->setStyleSheet(QStringLiteral("background-color: rgb(225, 225, 225);"));
        lbVar3->setAlignment(Qt::AlignCenter);
        lbVar1 = new QLabel(centralWidget);
        lbVar1->setObjectName(QStringLiteral("lbVar1"));
        lbVar1->setGeometry(QRect(1052, 130, 41, 20));
        lbVar1->setStyleSheet(QStringLiteral("background-color: rgb(225, 225, 225);"));
        lbVar1->setAlignment(Qt::AlignCenter);
        lbVar2 = new QLabel(centralWidget);
        lbVar2->setObjectName(QStringLiteral("lbVar2"));
        lbVar2->setGeometry(QRect(1101, 130, 41, 20));
        lbVar2->setStyleSheet(QStringLiteral("background-color: rgb(225, 225, 225);"));
        lbVar2->setAlignment(Qt::AlignCenter);
        leVariable3_2 = new QLineEdit(centralWidget);
        leVariable3_2->setObjectName(QStringLiteral("leVariable3_2"));
        leVariable3_2->setGeometry(QRect(1201, 100, 41, 22));
        leVariable1 = new QLineEdit(centralWidget);
        leVariable1->setObjectName(QStringLiteral("leVariable1"));
        leVariable1->setGeometry(QRect(1051, 100, 41, 22));
        lbVar3_2 = new QLabel(centralWidget);
        lbVar3_2->setObjectName(QStringLiteral("lbVar3_2"));
        lbVar3_2->setGeometry(QRect(1200, 130, 41, 20));
        lbVar3_2->setStyleSheet(QStringLiteral("background-color: rgb(225, 225, 225);"));
        lbVar3_2->setAlignment(Qt::AlignCenter);
        lbVar1_2 = new QLabel(centralWidget);
        lbVar1_2->setObjectName(QStringLiteral("lbVar1_2"));
        lbVar1_2->setGeometry(QRect(980, 100, 61, 31));
        lbVar1_2->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 90, 90);"));
        lbVar1_2->setAlignment(Qt::AlignCenter);
        lbVar3_3 = new QLabel(centralWidget);
        lbVar3_3->setObjectName(QStringLiteral("lbVar3_3"));
        lbVar3_3->setGeometry(QRect(1250, 130, 41, 20));
        lbVar3_3->setStyleSheet(QStringLiteral("background-color: rgb(225, 225, 225);"));
        lbVar3_3->setAlignment(Qt::AlignCenter);
        leVariable3_3 = new QLineEdit(centralWidget);
        leVariable3_3->setObjectName(QStringLiteral("leVariable3_3"));
        leVariable3_3->setGeometry(QRect(1250, 100, 41, 22));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1299, 26));
        menuBar->setStyleSheet(QLatin1String("background-color: rgb(55, 58, 72);\n"
"color: rgb(166, 156, 157);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 204, 204);"));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuFile->setStyleSheet(QStringLiteral(""));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        menuReferences = new QMenu(menuHelp);
        menuReferences->setObjectName(QStringLiteral("menuReferences"));
        menuEditor = new QMenu(menuBar);
        menuEditor->setObjectName(QStringLiteral("menuEditor"));
        MainWindow->setMenuBar(menuBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuEditor->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionAdd);
        menuFile->addAction(actionRemove);
        menuHelp->addAction(menuReferences->menuAction());
        menuHelp->addAction(actionAbout);
        menuReferences->addAction(actionGcode);
        menuReferences->addAction(actionSoftware);

        retranslateUi(MainWindow);

        pbExDeleteProgram->setDefault(true);
        pbAddGcode->setDefault(false);
        twDeltaManager->setCurrentIndex(1);
        tabWidget->setCurrentIndex(1);
        pbGrip->setDefault(false);
        pbPump->setDefault(false);
        twDeltaGeometry->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "IMWI - Delta X Software - Version 0.9", Q_NULLPTR));
        actionAdd->setText(QApplication::translate("MainWindow", "Add", Q_NULLPTR));
        actionRemove->setText(QApplication::translate("MainWindow", "Remove", Q_NULLPTR));
        actionAbout->setText(QApplication::translate("MainWindow", "About", Q_NULLPTR));
        actionGcode->setText(QApplication::translate("MainWindow", "Gcode", Q_NULLPTR));
        actionSoftware->setText(QApplication::translate("MainWindow", "Software", Q_NULLPTR));
        leExProgramName->setText(QApplication::translate("MainWindow", "Program 1", Q_NULLPTR));
        pbExDeleteProgram->setText(QString());
        lbExGCodeNumber->setText(QApplication::translate("MainWindow", "100 Gcode Lines", Q_NULLPTR));
        lbDebug->setText(QApplication::translate("MainWindow", "Debug :", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        pbExecuteGcodes->setToolTip(QApplication::translate("MainWindow", "Execute Gcode", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        pbExecuteGcodes->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbSaveGcode->setToolTip(QApplication::translate("MainWindow", "Save Gcode Into File", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        pbSaveGcode->setText(QString());
        pteGcodeArea->setPlainText(QApplication::translate("MainWindow", "G28\n"
"M03 S2000\n"
"M204 A4000", Q_NULLPTR));
        pbAddGcode->setText(QApplication::translate("MainWindow", "Add Gcode", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        pbFormat->setToolTip(QApplication::translate("MainWindow", "Format Gcode Lines", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        pbFormat->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbAddNewProgram->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbAddNewProgram->setText(QApplication::translate("MainWindow", "New", Q_NULLPTR));
        twDeltaManager->setTabText(twDeltaManager->indexOf(tab), QApplication::translate("MainWindow", "DeltaX 1", Q_NULLPTR));
        twDeltaManager->setTabText(twDeltaManager->indexOf(tab_3), QApplication::translate("MainWindow", "+", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        tabWidget->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        lbScreenStreamer->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbLoadCamera->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbLoadCamera->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbLoadTestImage->setToolTip(QApplication::translate("MainWindow", "Load Image", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        pbLoadTestImage->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbFilter->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbFilter->setText(QString());
        label_11->setText(QApplication::translate("MainWindow", "FPS", Q_NULLPTR));
        leFPS->setText(QApplication::translate("MainWindow", "15", Q_NULLPTR));
        lbTrackingObject->setText(QString());
        pbObjectRect->setText(QString());
        pbObjectLine->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbSwitchWorkFlow->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbSwitchWorkFlow->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbObjectOrigin->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbObjectOrigin->setText(QString());
        leXRec->setText(QApplication::translate("MainWindow", "57", Q_NULLPTR));
        leYRec->setText(QApplication::translate("MainWindow", "127", Q_NULLPTR));
        leRealDistance->setText(QApplication::translate("MainWindow", "300", Q_NULLPTR));
        leXCoordinate->setText(QApplication::translate("MainWindow", "-480", Q_NULLPTR));
        leYCoordinate->setText(QApplication::translate("MainWindow", "98", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        pbSelection->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbSelection->setText(QApplication::translate("MainWindow", "Process Area", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "mm", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        pbChangeXAxis->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pbChangeXAxis->setText(QString());
#ifndef QT_NO_TOOLTIP
        pbClearDetectObjects->setToolTip(QString());
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_STATUSTIP
        pbClearDetectObjects->setStatusTip(QString());
#endif // QT_NO_STATUSTIP
        pbClearDetectObjects->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tResultCameraArea), QApplication::translate("MainWindow", "Object Detecting", Q_NULLPTR));
        lbImageForDrawing->setText(QString());
        lbDrawingArea->setText(QString());
        leDrawingThreshold->setText(QApplication::translate("MainWindow", "150", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "Threshold", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "W: 208", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "H: 117", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "H Scale", Q_NULLPTR));
        leHeightScale->setText(QApplication::translate("MainWindow", "117", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "W Scale", Q_NULLPTR));
        leWidthScale->setText(QApplication::translate("MainWindow", "208", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "Ratio", Q_NULLPTR));
        lineEdit_11->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        pbSavePicture->setText(QString());
        pbDrawLine->setText(QString());
        pbDrawRectangle->setText(QString());
        pbDrawArc->setText(QString());
        pbDrawCircle->setText(QString());
        label_19->setText(QApplication::translate("MainWindow", "X", Q_NULLPTR));
        leDrawAg1->setText(QString());
        label_22->setText(QApplication::translate("MainWindow", "Y", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "H", Q_NULLPTR));
        label_25->setText(QApplication::translate("MainWindow", "W", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "O", Q_NULLPTR));
        pbOpenPicture->setText(QString());
        pbDeletePicture->setText(QString());
        pbExportDrawingGcodes->setText(QApplication::translate("MainWindow", "Export", Q_NULLPTR));
        pbPainting->setText(QString());
        cbDrawMethod->clear();
        cbDrawMethod->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Dot", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Line", Q_NULLPTR)
        );
        pbZoomIn->setText(QString());
        pbZoomOut->setText(QString());
        label_21->setText(QApplication::translate("MainWindow", "100%", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Drawing", Q_NULLPTR));
        pbHome->setText(QString());
        pbX->setText(QApplication::translate("MainWindow", "X", Q_NULLPTR));
        pbW->setText(QApplication::translate("MainWindow", "W", Q_NULLPTR));
        pbZ->setText(QApplication::translate("MainWindow", "Z", Q_NULLPTR));
        pbGrip->setText(QApplication::translate("MainWindow", "Grip", Q_NULLPTR));
        pbPump->setText(QApplication::translate("MainWindow", "Pump", Q_NULLPTR));
        twDeltaGeometry->setTabText(twDeltaGeometry->indexOf(t3D), QApplication::translate("MainWindow", "3D", Q_NULLPTR));
        twDeltaGeometry->setTabText(twDeltaGeometry->indexOf(t2D), QApplication::translate("MainWindow", "2D", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "mm", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "b", Q_NULLPTR));
        lineEdit_5->setText(QString());
        label->setText(QApplication::translate("MainWindow", "f", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "re", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "mm", Q_NULLPTR));
        lineEdit_4->setText(QString());
        label_5->setText(QApplication::translate("MainWindow", "mm", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "rf", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "mm", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "mm", Q_NULLPTR));
        lineEdit_7->setText(QString());
        lineEdit_8->setText(QString());
        lineEdit_6->setText(QString());
        label_7->setText(QApplication::translate("MainWindow", "e", Q_NULLPTR));
        twDeltaGeometry->setTabText(twDeltaGeometry->indexOf(tParameter), QApplication::translate("MainWindow", "Parameter", Q_NULLPTR));
        pbConnect->setText(QApplication::translate("MainWindow", "Connect", Q_NULLPTR));
        pbY->setText(QApplication::translate("MainWindow", "Y", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        pbGcodeReference->setToolTip(QApplication::translate("MainWindow", "Gcode Reference", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        pbGcodeReference->setText(QString());
#ifndef QT_NO_STATUSTIP
        pbSetSpeedConvenyor->setStatusTip(QString());
#endif // QT_NO_STATUSTIP
        pbSetSpeedConvenyor->setText(QApplication::translate("MainWindow", "C speed", Q_NULLPTR));
        leConvenyorSpeed->setText(QApplication::translate("MainWindow", "10", Q_NULLPTR));
#ifndef QT_NO_STATUSTIP
        pbGetPositionConvenyor->setStatusTip(QString());
#endif // QT_NO_STATUSTIP
        pbGetPositionConvenyor->setText(QApplication::translate("MainWindow", "C position", Q_NULLPTR));
        leConvenPosInterval->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        cbEnoughGetConvenyorContinues->setText(QApplication::translate("MainWindow", "UCP", Q_NULLPTR));
        cbGcode->clear();
        cbGcode->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "G01", Q_NULLPTR)
         << QApplication::translate("MainWindow", "G02", Q_NULLPTR)
         << QApplication::translate("MainWindow", "G03", Q_NULLPTR)
         << QApplication::translate("MainWindow", "G05", Q_NULLPTR)
         << QApplication::translate("MainWindow", "G28", Q_NULLPTR)
         << QApplication::translate("MainWindow", "M03", Q_NULLPTR)
         << QApplication::translate("MainWindow", "M04", Q_NULLPTR)
         << QApplication::translate("MainWindow", "M05", Q_NULLPTR)
         << QApplication::translate("MainWindow", "M204", Q_NULLPTR)
        );
        leAg1->setText(QString());
        lbAg1->setText(QApplication::translate("MainWindow", "X", Q_NULLPTR));
        leAg2->setText(QString());
        lbAg2->setText(QApplication::translate("MainWindow", "Y", Q_NULLPTR));
        lbAg3->setText(QApplication::translate("MainWindow", "Z", Q_NULLPTR));
        leAg3->setText(QString());
        lbAg4->setText(QApplication::translate("MainWindow", "W", Q_NULLPTR));
        leAg4->setText(QString());
        lbAg5->setText(QApplication::translate("MainWindow", "F", Q_NULLPTR));
        leAg5->setText(QString());
        leAg6->setText(QString());
        lbAg6->setText(QString());
        leVariable3->setText(QApplication::translate("MainWindow", "#Z", Q_NULLPTR));
        leVariable2->setText(QApplication::translate("MainWindow", "#Y", Q_NULLPTR));
        lbVar3->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        lbVar1->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        lbVar2->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        leVariable3_2->setText(QApplication::translate("MainWindow", "#1010", Q_NULLPTR));
        leVariable1->setText(QApplication::translate("MainWindow", "#X", Q_NULLPTR));
        lbVar3_2->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        lbVar1_2->setText(QApplication::translate("MainWindow", "Variables", Q_NULLPTR));
        lbVar3_3->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        leVariable3_3->setText(QApplication::translate("MainWindow", "#1011", Q_NULLPTR));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", Q_NULLPTR));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", Q_NULLPTR));
        menuReferences->setTitle(QApplication::translate("MainWindow", "References", Q_NULLPTR));
        menuEditor->setTitle(QApplication::translate("MainWindow", "Editor", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
